<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>name</key>
	<string>65816</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b(?i:ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRA|BRK|BRL|BVC|BVS|CLC|CLD|CLI|CLV|CMP|COP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JML|JMP|JSL|JSR|LDA|LDX|LDY|LSR|MVN|MVP|NOP|ORA|PEA|PEI|PER|PHA|PHB|PHD|PHK|PHP|PHX|PHY|PLA|PLB|PLD|PLP|PLX|PLY|REP|ROL|ROR|RTI|RTL|RTS|SBC|SEC|SED|SEI|SEP|STA|STP|STX|STY|STZ|TAX|TAY|TCD|TCS|TDC|TRB|TSB|TSC|TSX|TXA|TXS|TXY|TYA|TYX|WAI|WDM|XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>M6502</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.6502</string>
		</dict>
		<key>M65816</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRL|COP|JML|JSL|MVN|MVP|PEA|PEI|PER|PHB|PHD|PHK|PLB|PLD|REP|RTL|SEP|TCD|TCS|TDC|TSC|TXY|TYX|WDM|XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816</string>
		</dict>
		<key>M65C02</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRA|PHX|PHY|PLX|PLY|STP|STZ|TRB|TSB|WAI)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65c02</string>
		</dict>
		<key>binary_number</key>
		<dict>
			<key>match</key>
			<string>%[01]+</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<key>decimal_number</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<key>hex_number</key>
		<dict>
			<key>match</key>
			<string>\$[A-Za-z0-9]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<key>long_mnemonics</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADCL|ANDL|CMPL|EORL|LDAL|ORAL|SBCL|STAL)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.long</string>
		</dict>
		<key>octal_number</key>
		<dict>
			<key>match</key>
			<string>@([0-7]+)\b</string>
			<key>name</key>
			<string>constant.numeric.octal</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asm.65816</string>
	<key>uuid</key>
	<string>9CD14531-F337-4CB9-AB6C-8FD61F2C0CCC</string>
</dict>
</plist>
