<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>aii</string>
	</array>
	<key>isDisabled</key>
	<false/>
	<key>name</key>
	<string>MPW Asm IIgs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#M6502</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65C02</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#binary_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decimal_number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BLT|BGE|CPA|DEA|INA|SWA|TAS|TSA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.alt</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rockwell/m740</string>
			<key>match</key>
			<string>\b(?:BBC|BBR|BBS|CLB|RMB|SEB|SMB)[0-9]\b</string>
			<key>name</key>
			<string>keyword.mnemonic.other</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rockwell/m740</string>
			<key>match</key>
			<string>\b(?i:CLT|COM|LDM|RRF|SETT|TST)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.other</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([A-Za-z@_~][A-Za-z0-9@_~%$#]*)\s+((?i)PROC|PROCNAME|FUNC|INIT|STACKDP)\b</string>
			<key>name</key>
			<string>meta.function</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)ENTRY)\s+([A-Za-z@_~][A-Za-z0-9@_~%$#]*)\b</string>
			<key>name</key>
			<string>meta.entry</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.record</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([A-Za-z@_~][A-Za-z0-9@_~%$#]*)\s+((?i)RECORD)\b</string>
			<key>name</key>
			<string>meta.record</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z@_~][A-Za-z0-9@_~%$#]*\b</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=,)([xXyYsS])\b</string>
			<key>name</key>
			<string>variable.language.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:NOT|DIV|MOD|AND|OR|XOR|EOR)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[*;].*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=&lt;&gt;+-/|*#()^]|(&lt;&gt;|&lt;=|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:NOT|DIV|MOD|AND|OR|XOR|EOR)\b</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)MACRO)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>enable &amp;# macro parameters w/in a MAC ... ^^^ definition.</string>
			<key>end</key>
			<string>\b((?i)ENDMACRO|ENDM|MEND)\b</string>
			<key>name</key>
			<string>meta.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;[A-Za-z][A-Za-z0-9]*</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: LONGA ON</string>
			<key>match</key>
			<string>\b((?i)CODECHK|DATACHK|LONGA|LONGI|MSB)\s+((?i)ON|OFF)\b</string>
			<key>name</key>
			<string>meta.onoff.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)STRING)\s+((?i)ASIS|PASCAL|C|GS/OS)\b</string>
			<key>name</key>
			<string>meta.string.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)BLANKS)\s+((?i)ON|OFF|YES|NO|Y|N)\b</string>
			<key>name</key>
			<string>meta.blanks.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)BLANKS)\s+((?i)ON|OFF|YES|NO|Y|N|OBJECT|OBJ)\b</string>
			<key>name</key>
			<string>meta.case.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)MACHINE)\s+((?i)M65816|M6502|M65C02|M65CX02|M740)\b</string>
			<key>name</key>
			<string>meta.machine.directive</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)PRINT)\b</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.print.directive</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>;.*</string>
					<key>name</key>
					<string>comment.line</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:ON|OFF|PUSH|POP)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(?i:NO)?(?i:GEN|PAGE|WARN|MCALL|OBJ|DATA|MDIR|HDR|LITS|STAT|SYM)\b</string>
					<key>name</key>
					<string>constant.language</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^,\t ]</string>
					<key>name</key>
					<string>invalid.illegal.operand</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ALIGN|BLANKS|CASE|CODE|CODECHK|DATACHK|DIRECT|DUMP|EJECT|END|ENDF|ENDFUNC|ENDI|ENDP|ENDPROC|END_PROC|ENDR|ENDSTACK|ENDS|ENDWITH|ENTRY|EQU|EXPORT|FUNC|IMPORT|INCLUDE|INIT|LOAD|LONGA|LONGI|MACHINE|MSB|ORG|PAGESIZE|PRINT|PROC|RECORD|SEG|SEGATTR|SET|SPACE|STACKDP|STRING|TITLE|WITH)\b</string>
			<key>name</key>
			<string>keyword.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive.data</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)DC|DCB|DS)([.](.))?\b</string>
			<key>name</key>
			<string>meta.dc.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ACTR|AERROR|ANOP|CYCLE|ELSE|ELSEIF|ENDIF|ENDM|ENDMACRO|ENDWHILE|EXITM|GOTO|IF|LEAVE|MACRO|MEND|MEXIT|THEN|WHILE|WRITE|WRITELN|SET|SETA|SETC)\b</string>
			<key>name</key>
			<string>support.function.macro</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&amp;(?i:ABS|CHR|CONCAT|DEFAULT|DELSYMTBL|ENTERSYM|EVAL|FINDSYM|GETENV|INTTOSTR|I2S|ISINT|LEN|LEX|LIST|LOWCASE|LC|MAX|MIN|NBR|NEWSYMTBL|ORD|POS|SCANEQ|SCANNE|STRTOINT|S2I|SETTING|SUBSTR|SYSDATE|SYSINDEX|SYSLIST|SYSLST|SYSLOCAL|SYSGLOBAL|SYSMOD|SYSSEG|SYSTIME|SYSTOKEN|SYSTOKSTR|SYSVALUE|SYSFLAGS|TRIM|TYPE|UPCASE|UC)\b</string>
			<key>name</key>
			<string>support.function.macro</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>M6502</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.6502</string>
		</dict>
		<key>M65816</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRL|COP|JML|JSL|MVN|MVP|PEA|PEI|PER|PHB|PHD|PHK|PLB|PLD|REP|RTL|SEP|TCD|TCS|TDC|TSC|TXY|TYX|WDM|XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816</string>
		</dict>
		<key>M65816L</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADCL|ANDL|CMPL|EORL|LDAL|ORAL|SBCL|STAL)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.long</string>
		</dict>
		<key>M65C02</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRA|PHX|PHY|PLX|PLY|STP|STZ|TRB|TSB|WAI)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65c02</string>
		</dict>
		<key>binary_number</key>
		<dict>
			<key>match</key>
			<string>%[01]+</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<key>decimal_number</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<key>hex_number</key>
		<dict>
			<key>match</key>
			<string>\$[A-Fa-f0-9]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<key>octal_number</key>
		<dict>
			<key>match</key>
			<string>@([0-7]+)\b</string>
			<key>name</key>
			<string>constant.numeric.octal</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asm.65816.mpw</string>
	<key>uuid</key>
	<string>64362FB8-D779-440E-ABF7-5D238FF4A65D</string>
</dict>
</plist>
