<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
	</array>
	<key>name</key>
	<string>NinjaForce assembler</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.asm.65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#long_mnemonics</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#binary_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#decimal_number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BLT|BGE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.alt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\][A-Za-z][A-Za-z0-9_]*</string>
			<key>name</key>
			<string>entity.name.local</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b(?i:MAC)\b</string>
			<key>comment</key>
			<string>enable &amp;# macro parameters w/in a MAC ... ^^^ definition.</string>
			<key>end</key>
			<string>\^\^\^</string>
			<key>name</key>
			<string>support.macro</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>match</key>
					<string>&amp;\d+</string>
					<key>name</key>
					<string>variable.parameter</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)HEX)\b</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>HEX has a list of hex bytes w/o the $</string>
			<key>end</key>
			<string>$|;</string>
			<key>name</key>
			<string>meta.hex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b[0-9A-Fa-f]{1,2}\b</string>
					<key>name</key>
					<string>constant.numeric.hex</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=,)([xXyYsS])\b</string>
			<key>name</key>
			<string>variable.language.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ORG|EQU|DLW|DW|DFB|HEX|DS|MSB|COD|ASC|STR|TYP|IMP|INS|LNK|SHT|LNG|M08|M16|X08|X16|MAC|\^\^\^|LOP|&lt;&lt;&lt;|LST)\b</string>
			<key>name</key>
			<string>keyword.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[;*].*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[-+/*^&gt;&lt;|#\[\](),=]</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.65816.ninjaforce</string>
	<key>uuid</key>
	<string>F7ECC958-1B4C-4818-A28A-371799146151</string>
</dict>
</plist>
