<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>src</string>
		<string>s</string>
	</array>
	<key>name</key>
	<string>ORCA/M</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>source.asm.65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#binary_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#decimal_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>source.asm.65816#octal_number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BLT|BGE|CPA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.alt</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([_~A-Za-z][_~A-Za-z0-9]*)\s+((?i)START|DATA|PRIVDATA)\b</string>
			<key>name</key>
			<string>meta.function</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[*;!.].*</string>
			<key>name</key>
			<string>comment.line.m65816</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>actually this is position dependent...</string>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line.m65816</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[_~A-Za-z][_~A-Za-z0-9]*\b</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: LONGA ON</string>
			<key>match</key>
			<string>\b((?i)ABSADDR|CASE|CODECHK|DATACHECK|DYNCHK|ERR|EXPAND|IEEE|INSTIME|LIST|LONGA|LONGI|MSB|NUMSEX|OBJCASE|PRINTER|SYMBOL|65C02|65816)\s+((?i)ON|OFF)</string>
			<key>name</key>
			<string>meta.onoff.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other.path</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: KEEP pathname</string>
			<key>match</key>
			<string>\b((?i)APPEND|COPY|KEEP|MCOPY)\s+(\S*)</string>
			<key>name</key>
			<string>meta.path.directive</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)DC)\s+(\d*)([bB])(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>DC nB'...'</string>
			<key>end</key>
			<string>(')$</string>
			<key>name</key>
			<string>meta.dc.b</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[0|1]</string>
					<key>name</key>
					<string>constant.numeric.binary</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\S</string>
					<key>name</key>
					<string>invalid.illegal.binary</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)DC)\s+(\d*)([hH])(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>dc nH'...'</string>
			<key>end</key>
			<string>(')$</string>
			<key>name</key>
			<string>meta.dc.h</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[0-9A-Fa-f]</string>
					<key>name</key>
					<string>constant.numeric.hexidecimal</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\S</string>
					<key>name</key>
					<string>invalid.illegal.hexidecimal</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\b((?i)DC)\s+(\d*)([A-Za-z])(\d*)(')</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>storage.type</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>constant.numeric.decimal</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>DC nIn'...', DC C'...'</string>
			<key>contentName</key>
			<string>string.quited.single</string>
			<key>end</key>
			<string>(')|$</string>
			<key>name</key>
			<string>meta.dc.other</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:ABSADDR|ALIGN|ANOP|APPEND|CASE|CODECHK|COPY|DATA|DATACHK|DC|DIRECT|DS|DYNCHK|EJECT|END|ENTRY|EQU|ERR|EXPAND|GEQU|IEEE|INSTIME|KEEP|KIND|LIST|LONGA|LONGI|MCOPY|MEM|MERR|MSB|NUMSEX|OBJ|OBJCASE|OBJEND|ORG|PRINTER|PRIVATE|PRIVDATA|RENAME|SETCOM|START|SYMBOL|TITLE|USING|65C02|65816)\b</string>
			<key>name</key>
			<string>keyword.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b[aA]\b</string>
			<key>name</key>
			<string>variable.language.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=,)([xXyYsS])\b</string>
			<key>name</key>
			<string>variable.language.register</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[=&lt;&gt;+-/|*#()^\[\]]|(&lt;&gt;|&lt;=|&gt;=)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\.AND\.|\.EOR\.|\.OR\.)</string>
			<key>name</key>
			<string>keyword.operator</string>
		</dict>
		<dict>
			<key>match</key>
			<string>"[^"]*"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>match</key>
			<string>'[^']*'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm.65816.orcam</string>
	<key>uuid</key>
	<string>20FD91A7-4399-46D9-B4C6-B733A52F7B40</string>
</dict>
</plist>
