<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
	</array>
	<key>name</key>
	<string>WDC</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#M6502</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65C02</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65816</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#M65C02S</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#binary_number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#decimal_number</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:BGE|BLT|CPA|DEA|INA|RET|SWA|TAD|TAS|TDA|TSA|XOR)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.alt</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^[A-Za-z_~][A-Za-z0-9_~]*\b</string>
			<key>name</key>
			<string>entity.name.label</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>'</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.single</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.section</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^([A-Za-z_~][A-Za-z0-9_~]*)\s+((?i)SECTION)\b</string>
			<key>name</key>
			<string>meta.section</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.module</string>
				</dict>
			</dict>
			<key>match</key>
			<string>\b((?i)MODULE)\s([A-Za-z_~][A-Za-z0-9_~]*)\b</string>
			<key>name</key>
			<string>meta.module</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: LONGA ON</string>
			<key>match</key>
			<string>\b((?i)EXTERNS|GLOBALS|INCDEBUG|CASE|CHKIMMED|LONGA|LONGI|SPACES|BIT7|SQUOTES|TWOCHAR|ARGCHK|MACFIRST|INCLIST|CONDLIST|MACLIST|PASS1)\s+((?i)ON|OFF)\b</string>
			<key>name</key>
			<string>meta.onoff.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.language</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: CHIP 65816</string>
			<key>match</key>
			<string>\b((?i)CHIP)\s+((?i)65816|65C02|W65C02S)\b</string>
			<key>name</key>
			<string>meta.chip.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: CHIP 65816</string>
			<key>match</key>
			<string>\b((?i)MESSAGE|EXIT|HEADING|NAM|TITLE|TTL|STTL|SUBTITLE|SUBTTL)\s+(.*)$</string>
			<key>name</key>
			<string>meta.text.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.path</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: include path...</string>
			<key>match</key>
			<string>\b((?i)APPEND|INCLUDE|INSERT)\s+([^'" \t\r\n]+)</string>
			<key>name</key>
			<string>meta.file.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.unquoted</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>eg: string end w/ | or $</string>
			<key>match</key>
			<string>\b((?i)ASCII|ASC)\s+([^|\r\n]+)</string>
			<key>name</key>
			<string>meta.ascii.directive</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.directive</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.quoted.other</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>char text char</string>
			<key>match</key>
			<string>\b((?i)FCC)\s+((.)(.*?)(\3))</string>
			<key>name</key>
			<string>meta.fcc.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:APPEND|INCLUDE|INSERT|END|EXIT|MODULE|ENDMOD|SECTION|PAGE0|CODE|KDATA|DATA|UDATA|ENDS|ORG|ORIGIN|EQU|EQUAL|GEQU|DEFL|SET|VAR|EXTERN|EXTERNAL|XREF|EXTERNS|GLOBAL|PUBLIC|XDEF|GLOBALS|MESSAGE|MESSG|EFUNC|INCDEBUG|CASE|CHIP|CHKIMMED|COMMENT|DBREG|DPAGE|LONGA|LONGI|RADIX|SPACES|LLCHAR|BIT7|MASK|SQUOTE|TWOCHAR|ASCII|ASC|FCC|DATE|DA|BYTE|DB|DEFB|FCB|STRING|DC|DEFW|DW|FDB|WORD|DBYTE|DL|LONG|LONGW|LWORD|BLKB|BLKW|BLKL|DEFS|DS|RMB|DSA|DSB|DSL|DSW|APWDC|FLOAT|DOUBLE)\b</string>
			<key>name</key>
			<string>keyword.directive</string>
		</dict>
		<dict>
			<key>match</key>
			<string>;.*</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>M6502</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADC|AND|ASL|BCC|BCS|BEQ|BIT|BMI|BNE|BPL|BRK|BVC|BVS|CLC|CLD|CLI|CLV|CMP|CPX|CPY|DEC|DEX|DEY|EOR|INC|INX|INY|JMP|JSR|LDA|LDX|LDY|LSR|NOP|ORA|PHA|PHP|PLA|PLP|ROL|ROR|RTI|RTS|SBC|SEC|SED|SEI|STA|STX|STY|TAX|TAY|TSX|TXA|TXS|TYA)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.6502</string>
		</dict>
		<key>M65816</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRL|COP|JML|JSL|MVN|MVP|PEA|PEI|PER|PHB|PHD|PHK|PLB|PLD|REP|RTL|SEP|TCD|TCS|TDC|TSC|TXY|TYX|WDM|XBA|XCE)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816</string>
		</dict>
		<key>M65816L</key>
		<dict>
			<key>match</key>
			<string>\b(?i:ADCL|ANDL|CMPL|EORL|LDAL|ORAL|SBCL|STAL)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65816.long</string>
		</dict>
		<key>M65C02</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BRA|PHX|PHY|PLX|PLY|STP|STZ|TRB|TSB|WAI)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65c02</string>
		</dict>
		<key>M65C02S</key>
		<dict>
			<key>match</key>
			<string>\b(?i:BBR[0-7]|BBS[0-7]|RMB[0-7]|SMB[0-7])\b</string>
			<key>name</key>
			<string>keyword.mnemonic.65c02s</string>
		</dict>
		<key>binary_number</key>
		<dict>
			<key>match</key>
			<string>%[01]+</string>
			<key>name</key>
			<string>constant.numeric.binary</string>
		</dict>
		<key>decimal_number</key>
		<dict>
			<key>match</key>
			<string>\b([0-9]+)\b</string>
			<key>name</key>
			<string>constant.numeric.decimal</string>
		</dict>
		<key>hex_number</key>
		<dict>
			<key>match</key>
			<string>\$[A-Fa-f0-9]+</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<key>octal_number</key>
		<dict>
			<key>match</key>
			<string>@([0-7]+)\b</string>
			<key>name</key>
			<string>constant.numeric.octal</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.asm.65816.wdc</string>
	<key>uuid</key>
	<string>1D93031D-159C-4E7C-973B-2BD5370C3397</string>
</dict>
</plist>
